import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Movie Review App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ minHeight: "100vh", display: "flex", flexDirection: "column" }}
      >
        {/* Header */}
        <header
          style={{
            width: "100%",
            background: "#1e1e1e",
            padding: "12px 24px",
            display: "flex",
            justifyContent: "center",
            gap: "24px",
            boxShadow: "0 2px 10px rgba(0,0,0,0.3)",
            position: "sticky",
            top: 0,
            zIndex: 100,
          }}
        >
          <Link
            href="/home"
            style={{
              color: "white",
              fontWeight: "600",
              textDecoration: "none",
              fontSize: "1.1rem",
            }}
          >
            Home
          </Link>
          <Link
            href="/rated-movies"
            style={{
              color: "white",
              fontWeight: "600",
              textDecoration: "none",
              fontSize: "1.1rem",
            }}
          >
            ⭐ Rated Movies
          </Link>
        </header>

        {/* Main content */}
        <main style={{ flex: 1, width: "100%" }}>{children}</main>
      </body>
    </html>
  );
}
